project:
  type: book

book:
  title: "Climate adaptation"
  subtitle: "A billion dollar COP-out?"
  author:
    name: "Nils Nerhus Rørstad"
    email: "nnrorstad@gmail.com"
  date: "2025-09-16"
  downloads: pdf
  chapters:
    - index.qmd
    - quarto/abstract.qmd
    - quarto/intro.qmd
    - quarto/context.qmd
    - quarto/concepts.qmd
    - quarto/methods.qmd
    - quarto/findings.qmd
    - quarto/discussion.qmd
    - quarto/conclusion.qmd
    - quarto/references.qmd

cap-location: bottom
bibliography:
  - references.bib

execute:
  echo: false
  warning: false

format:
  html:
    theme: journal
    code-fold: true
    fig-width: 8
    fig-height: 4
    toc: FALSE
  pdf:
    documentclass: report
    fig-width: 8
    fig-height: 4
    toc: true
    number-sections: true
    number-depth: 2
    include-in-header:
      text: |
        \let\oldsection\section
        \renewcommand{\section}[1]{\clearpage\oldsection{#1}}
