project:
    type: book

book:
  title: "Adapting the Future"
  author: "Nils Nerhus RC8rstad"
  date: today
  downloads: [pdf,docx]
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters: 
        - chapters/intro.qmd
        - chapters/lit.qmd
        - chapters/scope.qmd
    - part: "Research design"
      chapters:
        - chapters/theory.qmd
        - chapters/methods.qmd
    - part: "Analysis"
      chapters:
        - chapters/findings.qmd
        - chapters/discussion.qmd
    - chapters/conclusion.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    number-depth: 2
  docx: 
    toc: true

editor: source