project:
    type: book

book:
  title: "Adapting the Future"
  author: "Nils Nerhus Rørstad"
  date: today
  downloads: [pdf,docx]
  chapters:
    - index.qmd
    - chapters/introduction.qmd
    - part: "Climate adaptation"
      chapters:
        - chapters/context.qmd
        - chapters/lit.qmd
    - part: "Research design"
      chapters:
        - chapters/theory.qmd
        - chapters/methods.qmd
    - part: "Analysis"
      chapters:
        - chapters/findings.qmd
        - chapters/discussion.qmd
    - chapters/conclusion.qmd

cap-location: margin
reference-location: margin
bibliography: references.bib
csl: apa.csl

execute: 
  echo: false
  warning: false

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    number-depth: 2
  docx: 
    toc: true

editor: source