project:
    type: book

book:
  title: "100 billion dollar COP-out"
  subtitle: "A critical analysis of the illusions and realities of climate adaptation"
  author: "Nils Nerhus Rørstad"
  date: today
  downloads: [pdf]
  chapters:
    - index.qmd
    - text/intro.qmd
    - part: "Climate adaptation"
      chapters:
        - text/context.qmd
        - text/lit.qmd
    - part: "Research design"
      chapters:
        - text/theory.qmd
        - text/methods.qmd
    - part: "Analysis"
      chapters:
        - text/findings.qmd
        - text/discussion.qmd
    - text/conclusion.qmd

cap-location: bottom
column: page-inset-shaded

bibliography: 
  - references/references.bib
  - references/grateful-refs.bib

execute: 
  echo: false
  warning: false

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt
    classoption:
      - a4paper
      - openright
      - cleardoublepage
    toc: true
    number-sections: true
    number-depth: 2

editor: source