project:
    type: book

book:
  title: "100 billion dollar COP-out"
  subtitle: "A critical analysis of the illusions and realities of climate adaptation"
  author: "Nils Nerhus Rørstad"
  date: today
  downloads: [pdf,docx]
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - part: "Climate adaptation"
      chapters:
        - chapters/context.qmd
        - chapters/lit.qmd
    - part: "Research design"
      chapters:
        - chapters/theory.qmd
        - chapters/methods.qmd
    - part: "Analysis"
      chapters:
        - chapters/findings.qmd
        - chapters/discussion.qmd
    - chapters/conclusion.qmd

cap-location: margin
bibliography: references.bib
csl: apa.csl
code-overflow: wrap
highlight-style: tango

execute: 
  echo: false
  warning: false
  freeze: auto

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    number-depth: 2
  docx: 
    toc: true

editor: source