project:
    type: book

book:
  title: "Adapting the Future"
  author: "Nils Nerhus Rørstad"
  date: today
  downloads: [pdf,docx]
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters: 
        - chapters/intro.qmd
        - chapters/lit.qmd
        - chapters/scope.qmd
    - part: "Research design"
      chapters:
        - chapters/theory.qmd
        - chapters/methods.qmd
    - part: "Analysis"
      chapters:
        - chapters/findings.qmd
        - chapters/discussion.qmd
    - chapters/conclusion.qmd

reference-location: margin
bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: cosmo
    
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    number-depth: 2
  docx: 
    toc: true

editor: source