project:
    type: book

book:
  title: "100 billion dollar COP-out"
  subtitle: "A critical analysis of the illusions and realities of climate adaptation"
  author: "Nils Nerhus Rørstad"
  date: today
  downloads: [pdf,docx]
  chapters:
    - index.qmd
    - text/intro.qmd
    - part: "Climate adaptation"
      chapters:
        - text/context.qmd
        - text/lit.qmd
    - part: "Research design"
      chapters:
        - text/theory.qmd
        - text/methods.qmd
    - part: "Analysis"
      chapters:
        - text/findings.qmd
        - text/discussion.qmd
    - text/conclusion.qmd

cap-location: bottom
bibliography: 
  - references/references.bib
  - references/grateful-refs.bib

csl: references/apa.csl
code-overflow: wrap
highlight-style: tango
code-fold: true

comments: 
  hypothesis: TRUE

execute: 
  echo: false
  warning: false
  freeze: auto

format:
  html:
    theme: cosmo
    code-fold: true
    include-before-body: _includes/page_metrics.html
  pdf:
    documentclass: scrreprt
    classoption:
      - a4paper
      - openright
      - cleardoublepage
    toc: true
    number-sections: true
    number-depth: 2
  docx: 
    toc: true
    reference-doc: references/custom-reference-doc.docx

editor: source