project:
    type: book

book:
  title: "Climate adaptation"
  subtitle: "A billion dollar COP-out?"
  author:
    name: "Nils Nerhus Rørstad"
    email: "202302046@post.au.dk"
  date: "2025-09-16"
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - text/intro.qmd
    - part: Background
      chapters:
        - text/context.qmd
        - text/concepts.qmd
    - part: Research design
      chapters:
        - text/methods.qmd
        - text/findings.qmd
    - part: Discussion
      chapters:
        - text/discussion.qmd
        - text/conclusion.qmd

cap-location: bottom
bibliography: 
  - references/references.bib
  - references/grateful-refs.bib
  
degree: "MSc in Human Security"
department: "Department of Culture and Society"  
university: "Aarhus University"
supervisor: "Assoc. Prof Michael Eilenberg"

execute: 
  echo: false
  warning: false

format:
  html:
    theme: journal
    code-fold: true
    fig-width: 8
    fig-height: 4
  pdf:
    documentclass: report
    fig-width: 8
    fig-height: 4
    fig-align: center
    toc: true
    number-sections: true
    number-depth: 2

editor: source