# Introduction

In January of 2025, as I am starting the process of writing this thesis, the people Los Angeles is feeling the extreme effects of a changing climate. As of today, 24 persons have died from the fires, and billions upon billions of assets have gone up in smoke. Irreplaceble art and music, stored in the homes of the elites that lived in Hollywood, are likely lost for ever.

As this thesis progresses, I will find more examples of climate disasters to write in this section. The floods in Spain are one good example to include. More likely than not, I should include the scenarios here, to give a taste of what is to come. 

## Climate security

Climate change is dangerous, unfair and already happening. Environmental security is a key pillar in the Human Security approach. Climate change is set to harm it.

Something about the shifting geopolitics meaning that the green transition is also somehow becoming securitized, and that the global polity is more concerned with the security-frame of international relations. Global south adaptation becoming a central part of the climate discourse, and as I will expand on in later in this thesis, it is unclear what it actually entails.

Climate security is a multi-level issue. Droughts, floods and other extremes caused by climate change could impact the livelihoods of many, and possible threaten peace and security in society at large. 

Security is also concerned with anticipating and avoiding risk. This means looking into the future. 

Climate adaptation is special because of its orientation to the future. It is a process of adaptation to risks of change. It is a reconstruction of the world to adapt to dangers that we do not know the full extent of. Most theory today assumes that climate adaptation can, and will come, as a win-win for people, climate and economy. 

In Scandinavia, climate security (klimasikring) and climate adaptation (klimatilpasning) is used interchangebly. I will use climate adaptation thorughout the rest of the thesis, because this is the language of the UNFCCC. 

## International climate change governance

While mitigating climate change perhaps is most important, adapting (and shielding) people, industries and nations from the risks of climate change is growing in prominence. At the 28th Conference of the Parties (COP28) to the United Nations Framework Convention for Climate Change (UNFCCC) in Dubai, an agreement was signed that the parties should make $1300 billon available, every year, for climate adaptation. 

Governments and civil society organizations around the world welcomed this, as the poorest in the world are the most vulnerable to climate change. Climate adaptation is therefore possibly becoming the new interface for financial aid between the Global North and the Global South. Most of the discourse around climate adaptation assumes many win-win scenarios. 

The UNFCCC has three pillars: Mitigation, adaptation and loss and damage [@hall2018]. 

The mitigation pillar has been a part of the UNFCCC since the Kyoto protocolls in [way back then], and is perhaps the most important part of the Convention. Since the Paris agreement (COP21) in 2015, all parties to the Convention has to submit Nationally Determined Contributions (NDCs) every five years.

Measures within the mitigation pillar span the whole economy, and is a process internal to every country, with the exeption of different carbon trading regimes, such as UN REDD+ or the European carbon trading system (ECTS). 

Climate adapation is measures aimed at limiting the damage caused by unmitigated climate change. It is, in a sense, the spillovereffect from unsuccessful mitigation.

Climate adaptation is at its simplest all infrastructure and change that is aimed at reducing the impacts of climate change [@ensor2009]. Some expand this understanding to include exploiting the opportunities climate change can bring with it [@vanhala2016]. This definition makes it possible to frame most infrastructure development as climate adaptation measures [@toussaint2021]. Climate adaptation is largely financed by the state where the infrastructure is built, although a larger degree of ODA is spent on climate adaptation related infrastructure [@dewan2022].

Loss and damage is the newest pillar, and its distinction from climate adaptation is muddied. When it was first brought it up, it was intended as a formalized and legalized form of climate compensation. It was supposed to pay for losses and damages that occurred beyond the limits of adaptation [@janzen2021]. This is not the version adopted by the UNFCCC. Loss and damage is to be financed through the same channels as adaptation, and will be mainstreamed into development assistance [@scoville-simonds2020].

The logic of the UNFCCC then becomes: All countries must cut their emissions. The impacts of unmitigated climate change must be adapted and what is beyond adaptation must be paid for as damages. 

While the distinctions I present here are *true*, they are not popularly adapted, and as I will highligh in [@sec-nexus], many approaches to climate change seek to impact (or subvert) all pillars simultainously. 

Climate change finance is a billion-dollar industry, and scholars claim climate adaptation is increasingly being funded with funds from other policy areas [@scoville-simonds2020]. The money is funneled into a growing amount of international funds dedicated to climate adaptation, and existing projects are being recast as adaptation projects [@dewan2022; @paprocki2018].

This shift, and the shift to project work is well described in the literature, and something I will expand on below. Thus, the goal of this project is to better understand this shift on the global level, and attempt to chart out where climate adaptation is today, and how it will shape the future.

## Climate adaptation as a new paradigm

The Anthropology of Development, as the critical analysis of development actors and their projects has a long history. Thinkers like @ferguson1994 and his analysis of the *Anti-politics machine* in Lesotho and the discourse of underdevelopment in Latin America have highlighted and spurred research into why development seems to always miss targets and fail in predictable ways.

Scholars have recently begun the work of deconstructing the climate adaptation discourse. @paprocki2018 describes it as an *Adaptation regime* based on her field work in Bangladesh. She argues that some countries are constructed as climate vulnerable and therefore in need of climate adaptation and that this imaginary is closely related to other historical processes of colonialism. All societal issues are reduced to be climate related, and unavoidable. This dystopian imaginary builds the groundwork for extensive experimentation, since the dystopian outlook eliminates the possible downsides. This, she argues, leads to dispossession as land is taken for shrimp aquaculture and migration to the cities is promoted. The poor and vulnerable that were supposed to be helped, simply are not [@paprocki2018].

@dewan2022 further develops this, highlighting the building of dams and polders as flood protection. She argues the polders built as a climate adaptation measure, are the same as the old for flood protection, and are successful at acquiring funding. Climate adaptation was *the spice* that made their applications for funding work. The only issue was that the polders did not work. By blocking the seasonal flooding and draining, the rivers became silted and needed dredging, furthering the risk of floods [@dewan2022]. 

This will all sort under the *mitigation* pillar of the UNFCCC, the first of three. All actions taken to avoid global warming and the following climate change, falls into this category. That also includes taxes on emissions and renewable power, as well as many other more or less effective measures. 

The second pillar, adopted in [say, 2015] is climate *adaptation*. It involves all measures taken to avoid the causes of global warming. Building sea walls to keep storm surges out of urban areas, shielding argiculture from exsessive rain

The third of the UNFCCC, adpoted in [say, 2022] is *loss and damage*, conserning all damages from global warming that are beyond adaptation. This pillar is highly disputed, as it was originally proposed as a way of bringing a judicial understanding of climate justice into play, where countries could sue other countries for the losses and damages their emissions had caused. While this is not the understanding adapted by the UNFCCC, where it is just seen as another form of climate adaptation.

