# Introduction {#sec-intro}

This thesis concludes five years spent at the University. Throughout this time, the world has changed dramatically:

- In 2020, the pandemic struck. [...]
- In 2022, Russia invaded Ukraine [...]
- In 2024, Israel responded to Hamas' terror attack with a full scale invasion [...]

At the same time, the world has started experiencing the results of 200 years of greenhouse emissions:

- Floods in Germany and Spain [...]
- Kiribati to buy land abroad [...]
- Wildfires in LA [...]

As I will expand on in the next section this has led to changes in international climate change governance as well. 

## Climate security as Human Security

With the popularization of the Human Security framework by the United Nations Development Program (UNDP) in the 1990s, the understanding of security expanded from its historical roots focussing exclusively on sovereignty and the State. It expanded vertically, to include common goods such as ecosystems and the biosphere and individuals, and horizontally, to include food security, environment security and community security, amongst others.

Security was conceptualized as "Freedom from want and freedom from fear". The idea was one person struggling somewhere, could be the one to create insecurity somewhere else. In this way, no one would be secure until everyone was secure. 

Climate change is set to inflict real losses and do real damage to the biosphere, countries and individuals. As climate change is a trans-scalar, global issues, adapting to it will similarly be trans-scalar and global. With its interdisciplinary and interconnected understanding of security, climate security fits well within the environmental security pillar of the Human Security framework one of the seven key pillars of the Human Security framework.

Climate adaptation is special because of its orientation to the future. It is unclear how severe, how often, in what kind and where the damages will come. It is a reconstruction without destruction. It relies on both the forecasts from climate science, as well as a specific understandings of the future, to decide what society is going to keep and discard. 

How we decide to frame the risk, vulnerability and tool we use to safeguard ourself from the future, is an inherently ontological and epistemological question. Without a proper understanding of climate adaptation, we run the risk of maladaptation, where the vulnerability to climate damage is not minimized, just moved around. 

## Scope

his thesis seeks to understand climate adaptation funding flows, on a global scale. Since this funding, and its discourse, is anchored in the UNFCCC ^[There is an argument to be made that the Norwegian economy is suppresed by the phenomenon known as "Dutch Disease", where one very large export sector hampers growth in all the others], it is a natural focal point for the study. The declarations made at the end of every Climate Summit are the outcome of intense negotiations at the summit, and their contents become a part national political debates all around the world. 

The UNFCCC is also the stage where climate-related are launched, and a meeting place for activists, lobbyists, decision-makers and experts. The National Adaptation plans are a part of this, where a World Bank supported project has 

What is climate adaptation?

- How has climate adaptation evolved at the UNFCCC?
- What is the impact of cllimate adaptation on are North-South finance flows?
- What are the most common climate adaptation interventions? What do they replace?

I intend to answer these question by analyzing flows in the OECD DAC CRS dataset ^[While it excludes fossil fuels from the future, it does not conceptually choose between technologies]. The first question would be answered by modelling the relationship between the climate adaptation marker and the funding flows. The second question will be answered in the same dataset, looking at the relationship between the OECD sectors and the marker. The last one will look at the relationship between development funders ^[See all these many sources that claim that climate adaptation could also be] and the climate adaptation marker. 

How will climate adaptation shape the future?

- What futures do climate adaptation projects have? What are their implications?
- How are climate adaptation interventions justified? Who decides?
- How could climate adaptation be reimagined? What are the alternatives?

I intend to answer these questions by analyzing the English language National Adaptation Plans (NAPs) submitted at the UNFCCC. The analysis will be layered and aim to deconstruct the visions of the future expressed in the texts. I identify the key methphors underpinning the adaptation discourse.

Lastly, based on these methaphors, I construct three scenarios for the future of climate adaptation. One where the trends continues as I found the first research question, one where *protection* is prioritized and one where *capacity* is prioritized.

## Structure of the thesis

This thesis is structured in three parts. Following this motivation section, the introduction continues, laying out the context, earlier research and scope of the thesis. [...]

In the second part, the research design will be presented. There, I will explain the different ontological and epistemological views on the future and my regression analysis and structured topic models [...]

In the third part, I will present the findings from my study and discuss how they should be understood, before I conclude the thesis. [...]