on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv
 
      - name: Cache renv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Cache TinyTeX
        id: tinytex-cache
        uses: actions/cache@v4
        with:
          path: ~/.TinyTeX
          key: ${{ runner.os }}-tinytex-v1

      - name: Set up TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
        if: steps.tinytex-cache.outputs.cache-hit != 'true'

      - name: Render and publish to GitHub pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
