on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Cache R packages
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          
      - name: Cache TinyTeX
        id: tinytex-cache
        uses: actions/cache@v3
        with:
          path: ~/.TinyTeX
          key: ${{ runner.os }}-tinytex-v1
          
      - name: Install TinyTeX    
        uses: r-lib/actions/setup-tinytex@v2
        if: steps.tinytex-cache.outputs.cache-hit != 'true'
      
      - name: Install LaTeX packages
        run: |
          if [ "${{ steps.tinytex-cache.outputs.cache-hit }}" != 'true' ]; then
            Rscript -e "tinytex::tlmgr_install(c('tufte-latex', 'xifthen', 'ifmtarg', 'hardwrap', 'titlesec', 'letterspace'))"
          fi
  
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}