on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache R environment
        uses: actions/cache@v4
        id: r-env-cache
        with:
          path: |
            ~/.local/share/renv
            ~/.TinyTeX
            ~/.R
            ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-env-${{ hashFiles('**/renv.lock') }}-${{ hashFiles('.github/workflows/nap_processing.yml') }}
          restore-keys: |
            ${{ runner.os }}-r-env-${{ hashFiles('**/renv.lock') }}-
            ${{ runner.os }}-r-env-
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up system dependencies
        if: steps.r-env-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libpoppler-cpp-dev \
            libgdal-dev \
            libproj-dev \
            libgeos-dev
 
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with: 
          tinytex: true

      - name: Render and publish to GitHub pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
