name: Update NAP Data

on:
  schedule:
    # Run every 14 days (1st and 15th of each month) at 3:00 AM UTC
    - cron: '0 3 1,15 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-nap-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
            use-public-rspm: true

      - name: Set up system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libpoppler-cpp-dev

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
          
      - name: Run the functions
        run: |
          Rscript script/nap_ent.R
          
      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add data/
          git diff --cached --quiet || git commit -m "Update NAP results"
          
          # Push changes to the correct branch
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        continue-on-error: true
