name: Update NAP Data

on:
  schedule:
    # Run every 14 days (1st and 15th of each month) at 3:00 AM UTC
    - cron: '0 3 1,15 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-nap-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}


    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install all dependencies from DESCRIPTION
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
      - name: Run the functions
        run: |
          Rscript scripts/nap_pipeline.R

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add data/
          git diff --cached --quiet || git commit -m "Update NAP results"
          git push
        continue-on-error: true
