on:
  workflow_dispatch:
  push:
    branches: main

name: Render project

jobs:
  render_project:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install all dependencies from DESCRIPTION
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with: 
          tinytex: true

      - name: Run NAP pipeline
        run: |
          Rscript scripts/nap_pipeline.R
        shell: bash

      - name: Render and publish to GitHub pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}