name: Run NAP functions

on:
  workflow_dispatch:

jobs:
  run-nap-functions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Set up system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libpoppler-cpp-dev \
            libgdal-dev \
            libproj-dev \
            libgeos-dev

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
          
      - name: Run analysis script
        run: |
          Rscript script/nap_ent.R
          
      - name: Commit and push results
        run: |
          # Configure Git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add results to git and commit if there are changes
          git add data/
          git diff --cached --quiet || git commit -m "Update NAP analysis results [skip ci]"
          
          # Push changes to the correct branch
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        continue-on-error: true
